### ISSUE TITLE
Update to Pixelmon 9.2.6

### ISSUE THREAD

**Issue by byrra** [GsTio86/PokeSync#1]
Could you please update to the newer version, im happy to test.

**Comment by GsTio86** [comment]
The new version should work fine, pixelmon's api doesn't break them

**Comment by byrra** [comment]
I will move the conversation from the Discord here as thats the right place.

As i said i will test Mohist, in Mohist the HuskSync doesnt work at all, probably due to the hybrid server.
On Arclight Husksync works fine with no errors, pokesync thinks its working but its not syncing any data, no party, pc etc.
Playerdumps from yesterday.
https://mclo.gs/Y9TvZ7Z
https://mclo.gs/pQQ25Tn

i have also tested this in a non velicity envoirment but its also not working there.

Server Logs:
Server 1 Debug: https://mclo.gs/HRtxnZ7
Server 1 Latest: https://mclo.gs/kxdqVyj
Server 2 Debug: https://mclo.gs/Hg3Qxhn
Server 2 Latest: https://mclo.gs/PaWGNM7

**Comment by byrra** [comment]
i also just tested with husksync 3.1 as the implementation states in your code.
    implementation "net.william278:husksync:3.1-cae17f6"
also didnt work.

**Comment by GsTio86** [comment]
After testing, I found that it was caused by HuskSync's event priority error. I have reported it to the developers and will fix it in the next version.
I'll also do more complete testing and I'll release version 2.4 tomorrow

**Comment by byrra** [comment]
will send me the new version and it is working with that version. thanks!

**Comment by GsTio86** [comment]
The new version of PokeSync fixed some minor problems, but you have to wait for HuskSync to release new jars, or compile it yourself
Now it works fine, here is the [demo](https://gyazo.com/1cb4d0b867cf2de7a78308cf1db3b1bd)

**Comment by GsTio86** [comment]
#https://github.com/WiIIiam278/HuskSync/commit/12e223618dd1eb45798c6d17dd974e393359d064
#https://github.com/GsTio86/PokeSync/compare/2.3.0...2.4.0
